# Practical_6: Numpy

---

### Exercise 1:
Create a NumPy array of integers from 1 to 10.

```python
# Exercise 1
```

In [149]:
num_matrix = np.array(range(1,10))
print(num_matrix)

[1 2 3 4 5 6 7 8 9]


---

### Exercise 2:
Create a 3x3 NumPy array filled with zeros.

```python
# Exercise 2
```

In [168]:
zero_mat = np.zeros((3,3))
print(zero_mat)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


---

### Exercise 3:
Create a NumPy array of 10 evenly spaced numbers between 0 and 5.

```python
# Exercise 3
```

In [171]:
spaced_mat =np.linspace(0,5,10)
print(spaced_mat)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


---

### Exercise 4:
Create a 5x5 identity matrix using NumPy.

```python
# Exercise 4
```

In [172]:
mat5=np.array(range(1,50,2)).reshape(5,5)
print(mat5)

[[ 1  3  5  7  9]
 [11 13 15 17 19]
 [21 23 25 27 29]
 [31 33 35 37 39]
 [41 43 45 47 49]]


---

### Exercise 5:
Create a 4x4 matrix with random values between 0 and 1.

```python
# Exercise 5
```

In [175]:
matB=np.linspace(0,1,16)#evenly spaced matrix
print(matB.reshape(4,4))

[[0.         0.06666667 0.13333333 0.2       ]
 [0.26666667 0.33333333 0.4        0.46666667]
 [0.53333333 0.6        0.66666667 0.73333333]
 [0.8        0.86666667 0.93333333 1.        ]]


---

### Exercise 6:
Find the shape of a NumPy array.

```python
# Exercise 6
```

In [147]:
y = Mat4.reshape(4,4)
np.shape(y) #This is a 4x4 matrix

(4, 4)

---

### Exercise 7:
Reshape a 1D NumPy array of 16 elements into a 4x4 matrix.

```python
# Exercise 7
```

In [146]:
Mat4=np.array(range(16))
print(Mat4.reshape(4,4))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


---

### Exercise 8:
Find the data type of the elements in a NumPy array.

```python
# Exercise 8
```

In [143]:
matrixA = np.array(range(1,10)).reshape(3,3)
for i in matrixA:
    type(i)
print(type(i))
print(type(matrixA[1,0])) 

<class 'numpy.ndarray'>
<class 'numpy.int64'>


---

### Exercise 9:
Create a NumPy array of integers from 1 to 100 and find all even numbers in the array.

```python
# Exercise 9
```

In [133]:
m_A=np.array(range(2,101)) #creating the array
print(m_A[::2]) #printing only even numbers

[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


---

### Exercise 10:
Generate a 6x6 matrix of random integers between 10 and 50.

```python
# Exercise 10
```

In [3]:
import numpy as np
A =np.random.randint(10,50,(6,6))
print(A)

[[24 34 26 21 15 13]
 [34 44 30 10 23 31]
 [34 10 29 14 37 31]
 [20 49 20 41 24 34]
 [32 29 24 10 43 36]
 [42 32 33 22 26 41]]


---

### Exercise 11:
Slice a 2D NumPy array to extract a submatrix.

```python
# Exercise 11
```

In [27]:
two_dim=np.array(range(1,7)).reshape(2,3)
sub_matrix =[two_dim[1,][:2],two_dim[0,][1:]]
print(np.array(sub_matrix))

[[4 5]
 [2 3]]


---

### Exercise 12:
Calculate the sum of all elements in a NumPy array.

```python
# Exercise 12
```

In [35]:
two_dim2=np.array(range(1,10)).reshape(3,3)
sum1= np.sum(two_dim2)
print(two_dim2)

print("The sum of all the entries is : ",sum1)
print("The sum of each row the is : ",sum(two_dim2))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
The sum of all the entries is :  45
The sum of each row the is :  [12 15 18]


---

### Exercise 13:
Calculate the mean, median, and standard deviation of a NumPy array.

```python
# Exercise 13
```

In [58]:
two_dim2.size
mean= np.sum(two_dim2)/(two_dim2.size)
print("Te mean is: ",mean)
print("The standard deviatin is: ",np.std(two_dim2))

Te mean is:  5.0
The standard deviatin is:  2.581988897471611


---

### Exercise 14:
Find the maximum and minimum values in a NumPy array.

```python
# Exercise 14
```

In [63]:

m=np.max(two_dim2)
print("The max number is: ",m)
mi =np.min(two_dim2)
print("The min number is: ",mi)

The max number is:  9
The min number is:  1


---

### Exercise 15:
Create a NumPy array of 20 random integers and find the index of the maximum value.

```python
# Exercise 15
```

In [76]:
rand_matrix=np.random.randint(1,50,(1,20))
print(rand_matrix)
np.argmax(rand_matrix) # argmax tho show the index of the maxmum number

[[35  6  9  1 49 38 45  8  4 10  6 37  4  5 29  1 42 29 26 32]]


4

---

### Exercise 16:
Create a NumPy array and reverse its elements.

```python
# Exercise 16
```

In [78]:
#using our  matrix two_dim2
reverse_matrix=np.flip(two_dim2) # flip to reverse the matrix
print(reverse_matrix)


[[9 8 7]
 [6 5 4]
 [3 2 1]]


---

### Exercise 17:
Create a 3x3 matrix and multiply it element-wise by another 3x3 matrix.

```python
# Exercise 17
```

In [82]:
matrix_B=np.array([[1,2,0],[0,1,1],[2,-1,3]])
prod_matrix = np.dot(two_dim2,matrix_B) # matrix multiplication
print(prod_matrix)

[[ 7  1 11]
 [16  7 23]
 [25 13 35]]


---

### Exercise 18:
Create a diagonal matrix from a given 1D array.

```python
# Exercise 18
```

In [110]:
matrix_A = np.array(range(1,10))
daig = matrix_A*np.eye(9)
print(daig)

[[1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 3. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 4. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 5. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 6. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 7. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 8. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 9.]]


---

### Exercise 19:
Perform matrix multiplication on two 2D NumPy arrays.

```python
# Exercise 19
```

In [98]:
A=np.array([[1,2],[1,0]])
C=np.array([[1,0],[3,3]])
AxC= np.dot(A,C)
print(AxC)

[[7 6]
 [1 0]]


---

### Exercise 20:
Flatten a 2D NumPy array into a 1D array.

```python
# Exercise 20
```

In [123]:
# using the matrix AxC
print(AxC)
one_D = AxC.flatten('C')
print("The one dimensional matrix is: ",one_D)

[[7 6]
 [1 0]]
The one dimensional matrix is:  [7 6 1 0]
